### ISSUE TITLE
Load views from nib incorrect resize

### ISSUE THREAD

**Issue by stefanocdn** [ole/OLEContainerScrollView#9]
Views loaded from nib and added to the contentView are resized incorrectly (much bigger), is there a reason for that? I canno't find why

**Comment by macdrevx** [comment]
@jillhc and I just ran into a similar issue. Ultimately, what fixed it for us was making sure the views we added to the content view had `translatesAutoresizingMaskIntoConstraints = YES` and `autoresizingMask = UIViewAutoresizingNone`.

This prevented the subviews from resizing if they were added to the content view prior to the content view's size being adjusted in `-[OLEContainerScrollView layoutSubviews]`.

We only had this problem on devices with 480 pt-tall screens running iOS 7. The 568 pt-tall screens did not encounter the issue because the scroll view started out at the correct height when unarchived from the xib. On iOS 8, our particular usage ended up triggering layout that set the content view's height appropriately prior to when we added subviews. I'm not sure that this is guaranteed in the general case though—we may have just been "lucky".

@ole We think it would make sense for `OLEContainerScrollView` to ensure that all subviews added to the content view are set appropriately in this regard. Thoughts?

**Comment by ole** [comment]
@macdrevx Sorry for the late reply. I pushed a fix which works in my tests, although I chose to set `translatesAutoresizingMaskIntoConstraints = NO` because that makes more sense in my opinion. The container scroll view does not use autolayout internally so the subviews' autoresizing masks should really not be translated into layout constraints. Anyway, I hope this works for you. Thanks for the research.

**Comment by macdrevx** [comment]
@ole We tried `translatesAutoresizingMaskIntoConstraints = NO` initially as well, but we ran into issues with infinite recursion (on 8.2)/infinite layout loop (on 7.1) with something related to layout. Do you have any insight into what might cause that to happen?
